### PR TITLE
Uploaded Rasp Pi Container STL

### PR DESCRIPTION
**Pull request by gchhughes**

### CODE REVIEW

**Comment by williamchong256** [comment]
hey @Firius0408 could you take a look at this pull request? Griff just added two STL files to the CAD branch but when we try to merge it into the hardware branch it tries to upload all these other changes too. Could it be something to do with his local master branch not being up to date?

**Comment by Firius0408** [comment]
It's because the hardware branch is woefully stale

**Comment by Firius0408** [comment]
Do you want to start using the hardware branch again? I can reset it to main but there's 2 commits on it that are unique and idk what those commits are for

**Comment by Firius0408** [comment]
Actually I can just rebase hardware onto main branch. Do you want me to push that?

**Comment by williamchong256** [comment]
I think the two unique commits (b8a75a1 and 9f36421 right?) are the commits that Griff used to push STL files with. So if you want to you could just reset hardware to main and we could redo that. Either way shouldn't be a problem, just wasn't sure why this was occuring.

**Comment by williamchong256** [comment]
Otherwise for hardware maybe we could just directly merge PRs into main? What are your thoughts

**Comment by Firius0408** [comment]
Well because if you look at where the hardware branch is, it's at the very beginning of our git history. It branched off of main in November. So that's why. There's no issue with the CAD branch, it's just where the hardware branch is. The thing is there are 2 commits on the hardware branch that are unique from main, but I just squashed one out because it was a test commit and the other commit was mostly a duplicate of another commit on main. So I'll just rebase hardware onto main then.

**Comment by Firius0408** [comment]
> I think the two unique commits ([b8a75a1](https://github.com/williamchong256/immersive-sleep/commit/b8a75a1709fbbdf3ffb45f0e346c5666b590d772) and [9f36421](https://github.com/williamchong256/immersive-sleep/commit/9f36421feb02666a78fa27fa39880c2f7f03d07b) right?) are the commits that Griff used to push STL files with. So if you want to you could just reset hardware to main and we could redo that. Either way shouldn't be a problem, just wasn't sure why this was occuring.

Also there's only one commit on this branch...

EDIT: Ah I see commit b8a75a1 is already in the main branch, it got merged in with #92

**Comment by Firius0408** [comment]
If hardware is gonna upload files as essentially finished products like they have been doing so far, they can merge directly into main that's fine

**Comment by williamchong256** [comment]
Ok let's go ahead and do that then, thanks for the help

**Review by Firius0408 — APPROVED** [review]

**Review by williamchong256 — APPROVED** [review]

**Comment by williamchong256** [comment]
Let's keep the hardware branch for now, I'm thinking in the near future we might have more WIP sorts of hardware/sensor code.

**Pull request merged**
