### PR TITLE
Moved code files to src/

### LINKED ISSUE #69: Restructure repository files
As more and more components are implemented and more files are generated to house refactored components, it would make sense to organize files into subdirectories for a cleaner repository. Because there's no one right way to structure file and directory layout, I welcome other contributors to give their thoughts here. I'll likely link in a draft PR of how I would probably restructure our files for reference.

### PR DESCRIPTION
**Pull request by Firius0408**
Closes #69

### CODE REVIEW

**Review by williamchong256 — APPROVED** [review]
Yeah I like this idea; maybe we could also create a /data subdirectory to store test data files?

**Comment by williamchong256** [comment]
Perhaps we could also keep the style(s) in a separate subdirectory

**Comment by Firius0408** [comment]
Yeah I think there could definitely be more organization we can/should do which is why I wanted other members to put in their input before opening this up to be merged

**Comment by Firius0408** [comment]
@vinaynagappala I went ahead and merged in your 'settings' branch

**Comment by vinaynagappala** [comment]
Courtney and I were gonna push some more stuff to that, but it's cool. But now that the settings pages are all separated, does it make sense to put those in a separate 'settings' subdirectory? And putting the themes/styles in a separate subdirectory is cool.

**Review by vinaynagappala — APPROVED** [review]

**Comment by Firius0408** [comment]
@vinaynagappala Yeah you're welcome to make whatever changes you want. You can keep pushing to your branch if you want it doesn't matter, I can always merge it in again. You guys can also push commits to this branch as well if you want.

**Comment by Firius0408** [comment]
@vinaynagappala If you don't have any commits lined up for this branch yet I'm gonna go ahead and merge this into frontend.

**Pull request merged**
