### PR TITLE
Sign In Page Reformatting

### LINKED ISSUE #121: Reformat Sign In Page
Make the sign-in page clearer, by separating which inputs are for logging back in and which are for creating an account.

### PR DESCRIPTION
**Pull request by vinaynagappala**
Closes #121

### CODE REVIEW

**Review by Firius0408 — APPROVED** [review]
Nice haha totally forget my boilerplate code looks like crap. Also you don't have to reuse the username and password field if you don't want to. I think most apps have the log in page as like the default and then you can click on like a `register` button if you don't have an account yet and then it opens up a whole nother page. But it's up to you and we can always change it later down the road

**Comment by vinaynagappala** [comment]
Yeah, I was thinking about doing a separate signup page but this was easier lol. I will look into implementing that, so this PR can just sit for a while until I work that out

**Comment by Firius0408** [comment]
Or you can just merge it in too lol if we do change it then we do change it otherwise we don't. But might as well just merge this in so if we don't then there's at least still this.

**Comment by vinaynagappala** [comment]
smort will do

**Pull request merged**
