### PR TITLE
Integrate AWS Amplify into frontend

### LINKED ISSUE #84: Merge AWS Amplify code into frontend
Once #83 is finished, the AWS Amplify code can be merged into frontend.

### LINKED ISSUE #90: Remove backend GitHub Actions

### PR DESCRIPTION
**Pull request by Firius0408**
Closes #84

Will merge in once #83 is closed.

### CODE REVIEW

**Comment by Firius0408** [comment]
Will also close #90

**Comment by Firius0408** [comment]
Once I finish up the rest of the tasks needed for AWS Amplify integration, this PR will be merged in. See [AWS Integration Project](https://github.com/williamchong256/immersive-sleep/projects/2) for details.

**Comment by Firius0408** [comment]
@vinaynagappala Can you see if you can test these changes on your end and then we can get this onto main

**Comment by Firius0408** [comment]
@vinaynagappala bump

**Review by vinaynagappala — APPROVED** [review]
looks good!

**Pull request merged**
